version: '3.8'

services:
  wms_service_api:
    build: .  # Путь к Dockerfile FastAPI
    container_name: wms_service_api
    image: wms_service_api_image

    ports:
      - "8310:8010"
    networks:
      - vector_db_default  # Имя сети из docker inspect

networks:
  vector_db_default:
    external: true  # Используем существующую сеть